---
title: "BUSCO"
author: "Jill Ashey"
date: "2026-03-22"
output: html_document
---

BUSCO was run to evaluate completeness of our genome (Ptua), and other published POC genomes. This script will plot these results to compare completeness across Pocillopora spp. genomes.

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(forcats)
```

Load busco comparison data
```{r}
busco <- read.csv("../tables/POC_BUSCO_genome.csv")
```

Reshape data to long format 
```{r}
busco_long <- pivot_longer(busco, 
                           cols = c("Complete_single_copy_percent", "Complete_duplicate_percent", "Fragmented_percent", "Missing_percent"),
                           names_to = "Category",
                           values_to = "Percentage")
```

Reorder categories for plotting 
```{r}
# Rename and reorder categories
busco_reordered <- busco_long %>%
  mutate(Category = factor(Category,
                           levels = c("Complete_single_copy_percent", 
                                      "Complete_duplicate_percent", 
                                      "Fragmented_percent", 
                                      "Missing_percent"),
                           labels = c("Complete & single copy (Cs)",
                                      "Complete & duplicate copy (Cd)",
                                      "Fragmented (F)",
                                      "Missing (M)")),
         Species = factor(Species, 
                     levels = c("Pocillopora verrucosa", 
                                "Pocillopora damicornis", 
                                "Pocillopora acuta (Indonesia)", 
                                "Pocillopora acuta (Hawai'i)", 
                                "Pocillopora meandrina ", 
                                "Pocillopora tuahiniensis"))) %>%
  group_by(Species) %>%
  arrange(desc(Percentage), .by_group = TRUE) %>%
  ungroup()

# Create a separate dataframe for labels
label_data <- busco_reordered %>%
  distinct(Species) %>%
  group_by(Species) %>%
  dplyr::summarise(Label = case_when(
    Species == "Pocillopora tuahiniensis" ~ "Cs = 91.5%, Cd = 5.2%, F = 0.8%, M = 2.4%",
    Species == "Pocillopora meandrina " ~ "Cs = 94.9%, Cd = 1.2%, F = 2.0%, M = 1.9%",
    Species == "Pocillopora acuta (Hawai'i)" ~ "Cs = 93.6%, Cd = 2.5%, F = 1.9%, M = 2.0%",
    Species == "Pocillopora acuta (Indonesia)" ~ "Cs = 89.0%, Cd = 0.4%, F = 6.9%, M = 3.7%",
    Species == "Pocillopora damicornis" ~ "Cs = 90.5%, Cd = 0.2%, F = 4.2%, M = 5.1%",
    Species == "Pocillopora verrucosa" ~ "Cs = 92.0%, Cd = 2.9%, F = 2.5%, M = 2.5%",
    TRUE ~ ""
  ))
```

Plot! 
```{r}
ggplot(busco_reordered, aes(x = Species, y = Percentage, fill = fct_rev(Category))) +
  geom_bar(stat = "identity", position = "fill", width = 0.7, color = "black") +
  # geom_text(aes(label = ifelse(Species == "Acropora pulchra", "sup", "")),
  #           position = position_fill(vjust = 0.5),
  #           color = "white", size = 4, fontface = "bold") +
  geom_text(data = label_data, aes(x = Species, y = 0.5, label = Label), 
            color = "black", 
            size = 5,
            inherit.aes = F) +
  scale_y_continuous(labels = scales::percent_format(accuracy = 1), expand = c(0, 0)) +
  #scale_fill_manual(values = c("#00441b", "#238b45", "#66c2a4", "#b2e2e2")) +
  scale_fill_manual(values = c("#22223B", "#ADA7C9", "#C9ADA7", "#E8DAB2")) +
  coord_flip() +
  labs(x = NULL,
       y = "Percentage",
       fill = "BUSCO Category") +
  theme_minimal() +
  theme(
    axis.text.y = element_text(face = "italic", color = "black", size = 20),
    axis.title.x = element_text(size = 23),
    axis.text.x = element_text(color = "black", size = 20),
    legend.position = "right",
    legend.title = element_text(face = "bold"),
    #panel.grid.major.y = element_line(color = "black"),
    axis.line.y = element_line(color = "black"),
    panel.grid.major = element_line(color = "black"),
    panel.grid.minor = element_blank()) +
  guides(fill = guide_legend(reverse = TRUE))

# Save 
ggsave("../output/assembly/final/busco_comparisons.pdf", plot = last_plot(), width = 15, height = 10)
ggsave("../output/assembly/final/busco_comparisons.png", plot = last_plot(), width = 15, height = 10)
```

